actors:
  alice:
    image_url: /images/actors/Atsushi.png
    name: Atsushi
    url: http://sns.example.com/Atsushi
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: http://sns.example.com/bob
author: alice
description: 歯医者の日々の、独り言
description_long: 歯医者の目線で、日々の出来事、ちょっとしたお口の情報を届けるポッドキャスト
email: info@futabadc.jp
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: 歯医者
hashtag:　futaba
itunes_podcast_url:
keywords: 歯,歯科,歯医者,口
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 歯医者の独り言
url: http://example.com
